# Generated by Django 4.1.3 on 2022-12-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Katalog',
            fields=[
                ('idKatalog', models.BigAutoField(primary_key=True, serialize=False)),
                ('judulKatalog', models.CharField(max_length=30)),
                ('thumbnail', models.CharField(max_length=500)),
                ('deskripsiKatalog', models.TextField()),
                ('hargaKatalog', models.CharField(max_length=30)),
            ],
        ),
    ]
