# Generated by Django 4.1.3 on 2022-12-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('idPromo', models.BigAutoField(primary_key=True, serialize=False)),
                ('namaPromo', models.CharField(max_length=30)),
                ('gambarPromo', models.CharField(max_length=500)),
                ('detailsPromo', models.TextField()),
                ('tanggalExp', models.DateField()),
            ],
        ),
    ]
