# Generated by Django 4.0.4 on 2022-12-10 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Promo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promo',
            options={'ordering': ['tanggalExp']},
        ),
    ]
